import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="mb-6 flex gap-4 px-6">
          <Link href="/" className="text-sky-400">Home</Link>
          <Link href="/blog" className="text-sky-400">Blog</Link>
          <Link href="/services" className="text-sky-400">Services</Link>
          <Link href="/marketplace" className="text-sky-400">Marketplace</Link>
          <Link href="/contact" className="text-sky-400">Contact</Link>
          <Link href="/items" className="text-sky-400">Forms</Link>
          <Link href="/posts-demo" className="text-sky-400">Posts Demo</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}